# Working with Numpy

Numpy is the numerical python package, with a lot of mathematical capabilities. Before we can use it, we need to first import the package. We will import it under the name np such that we can afterwards refer to it by this short name.

In [10]:
# your code here
import numpy as np

In the cell below, generate two 2x3 array with all elements equal to 1 - assign one of the arrays to the variable a and the other one to b. Add the two arrays. What do you get?

In [13]:
# your code here a = np.random.random((10,4))
# np.random.random((2,3))

a = np.random.random((2,3)) * 1
b = np.random.random((2,3)) * 1

print(np.add(a, b))

[[1.60223288 1.77194272 1.48275898]
 [0.38885393 0.46980732 1.44431248]]


Now generate another array c which is a 3x2 array with all elements equal to 1. Are you able to add a and c? Why or why not?

In [14]:
# your code here
c = np.random.random((3,2)) * 1
print(np.add(a, c))

# the first(a) has matrix 2x3, while the latter (c) has 3,2, 
# hence, operands could not be broadcast together with shapes (2,3) (3,2) 

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

Transpose c so that it has the same structure of a (i.e. become a 2x3 array). Assign the transposed array to variable "d". Are you able to add a and d?

In [17]:
# your code here
d = np.random.random((2,3))
d
print(np.add(a,d))

[[1.63746433 1.44311259 1.40546912]
 [0.72368097 0.73326333 1.48481806]]


Which combination of arrays are you able to multiply with each other? Why?

In [18]:
# your code here
# Multiply elements of a and d together because they have the same 2,3 matrix size
print(np.multiply(a,d))

[[0.66524288 0.51574251 0.49225711]
 [0.06760943 0.10641565 0.55010352]]


Create a list which contains the numbers from 0 to 10. Square the list elementwise using numpy functions.

In [26]:
# your code here
num = np.random.random((3,5)) * 10
np.square(num)

array([[12.47934538,  9.78200932, 20.28856378, 34.43625935, 20.58910975],
       [ 4.57262727, 97.44171673, 68.74707042, 17.20198135, 36.67446548],
       [25.59810345,  2.64168319, 34.85606711, 40.80240347,  3.23594059]])

Create a numpy array of size 10x10 which has random numbers between 0 and 100 on the main diagonal and zeros otherwise.

In [23]:
# your code here
np.random.random((10,10)) * 100



array([[47.18089059, 30.71718227, 60.11608556, 20.28913466, 24.37082662,
        33.84278054, 49.48599775, 34.191858  , 59.40124467, 62.18308179],
       [54.92223843, 80.08716572, 18.2408713 , 90.18265936, 29.13211929,
        26.67092344,  9.02288001, 52.30440686, 83.23436521, 32.29649489],
       [71.68096108, 66.40248247, 40.61915726,  6.62104964, 33.10080356,
        58.42562662, 75.92654391, 88.41366872, 63.12576609, 27.29348104],
       [37.85762936, 23.69215384, 63.93434714,  9.62953482, 27.05963389,
        22.85060108, 26.18238863, 88.80079048, 36.42375161, 13.81063687],
       [86.62931629, 26.24239923,  1.34234817, 85.99396612, 64.19829771,
        46.51472369, 83.33396403, 30.35891986, 47.70385176, 12.75798641],
       [55.80296557, 35.98150073, 21.01745096,  6.98587754, 54.23907401,
        44.82722976,  7.22944233, 29.56768491, 28.62392361, 58.91397832],
       [95.25346033, 83.03995854, 38.17271768, 80.75339045, 70.04921113,
        17.12418724,  0.36495654, 27.13130642